#ifndef DEDISPERSION_PARAMETERS_H_
#define DEDISPERSION_PARAMETERS_H_

#define NUMREG      14
#define DIVINT      16
#define DIVINDM     40
#define FDIVINDM    80.0f

#define ARRAYSIZE DIVINT * DIVINDM

#endif // DEDISPERSION_PARAMETERS_H_
